//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mothernaturesfarm.web.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-01-01 21:00:00.00.
        /// </summary>
        public static string BDayPartyTimeEnd {
            get {
                return ResourceManager.GetString("BDayPartyTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-01-01 09:00:00.00.
        /// </summary>
        public static string BDayPartyTimeStart {
            get {
                return ResourceManager.GetString("BDayPartyTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $25.00.
        /// </summary>
        public static string FirePitCost {
            get {
                return ResourceManager.GetString("FirePitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-09-26 09:00:00.00.
        /// </summary>
        public static string OpeningDayDate {
            get {
                return ResourceManager.GetString("OpeningDayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $5.00.
        /// </summary>
        public static string PartyResCostPerAdult {
            get {
                return ResourceManager.GetString("PartyResCostPerAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $10.00.
        /// </summary>
        public static string PartyResCostPerChild {
            get {
                return ResourceManager.GetString("PartyResCostPerChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-09-26 09:00:00.00.
        /// </summary>
        public static string PumpkinPatchBeginDate {
            get {
                return ResourceManager.GetString("PumpkinPatchBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-10-31 21:00:00.00.
        /// </summary>
        public static string PumpkinPatchEndDate {
            get {
                return ResourceManager.GetString("PumpkinPatchEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $3.00.
        /// </summary>
        public static string SchoolTourCostPerAdult {
            get {
                return ResourceManager.GetString("SchoolTourCostPerAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $8.00.
        /// </summary>
        public static string SchoolTourCostPerChild {
            get {
                return ResourceManager.GetString("SchoolTourCostPerChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-10-01 09:00:00.00.
        /// </summary>
        public static string SchoolToursBeginDate {
            get {
                return ResourceManager.GetString("SchoolToursBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-10-31 18:00:00.00.
        /// </summary>
        public static string SchoolToursEndDate {
            get {
                return ResourceManager.GetString("SchoolToursEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-12-12 09:00:00.00.
        /// </summary>
        public static string SnowDayBeginDate {
            get {
                return ResourceManager.GetString("SnowDayBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $5.00.
        /// </summary>
        public static string SnowDayCostPerAdult {
            get {
                return ResourceManager.GetString("SnowDayCostPerAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $10.00.
        /// </summary>
        public static string SnowDayCostPerChild {
            get {
                return ResourceManager.GetString("SnowDayCostPerChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020-12-12 18:00:00.00.
        /// </summary>
        public static string SnowDayEndDate {
            get {
                return ResourceManager.GetString("SnowDayEndDate", resourceCulture);
            }
        }
    }
}
